### ISSUE TITLE
Documentation on BLE parts

### ISSUE THREAD

**Issue by chrysn** [openwch/ch32v307#7]
Judging by a full-text search of the Chinese datasheet (which should give at least an indication of the completeness until #6 is resolved), the BLE registers are documented to have the address space 0x40024000 to 0x40026000, but there is no further BLE documentation in the text.

Will this be added in a later revision, or are they available at a different location?

I'd be happy to work on this chip if its radio is documented.

**Comment by HouHou01** [comment]
First of all, thank you for your feedback.
In order to let customs develop easily, the BLE registers have been compiled in the form of a library. and all of the register setting can be modified through the API fuction.
The MCU chips with BLE function are ch583\ch32v208\ch573\ch571k... 
due to the problem of IC processing capacity.  ch32v208 will be released in the next almost 3 month~
At present,the CH583 would be a suitble choice (https://github.com/openwch/ch583).
